spring:
    application:
        name: upwork
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}
debug: ${DEBUG:false}
logging:
    level:
        org.springframework.boot.autoconfigure: ERROR
        org.springframework.core: ERROR