package com.activecourses.upwork.model;

public enum NotificationType {
    PROPOSAL_RECEIVED,
    PROPOSAL_ACCEPTED,
    PROPOSAL_REJECTED,
    CONTRACT_CREATED,
    CONTRACT_COMPLETED,
    CONTRACT_TERMINATED,
    MILESTONE_COMPLETED,
    PAYMENT_RECEIVED,
    PAYMENT_CREATED,
    REVIEW_RECEIVED,
    NEW_MESSAGE
}
